trigger:
  batch: true
  branches:
    include:
    - main
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - azure-pipelines/release.yml

stages:
- stage: Build
  variables:
    TreatWarningsAsErrors: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    BuildConfiguration: Release
    BuildPlatform: Any CPU
    codecov_token: e300ab17-4cd6-43b5-8292-e824cb320ed3
    ci_feed: OSS/PublicCI
    NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages
    GeneratePInvokesTxt: true
  jobs:
  - template: azure-pipelines/build.yml
