parameters:
- name: windowsPool
  type: object
  default:
    vmImage: windows-2022

jobs:
- job: Windows
  pool: ${{ parameters.windowsPool }}
  variables:
  - group: pinvoke code signing
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml

  - powershell: '& (./azure-pipelines/Get-nbgv.ps1) cloud -p src -c'
    displayName: Set build number

  - template: dotnet.yml
  - template: publish-deployables.yml
